services:
  - type: web
    name: lolhub-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
[]